version: '3.8'

services:
  web:
    build: .
    container_name: picklist-quotation-converter
    ports:
      - "${HOST_PORT:-5000}:5000"
    volumes:
      - ./data:/app/data
      - ./app:/app/app
    environment:
      - FLASK_ENV=${FLASK_ENV:-production}
      - PYTHONUNBUFFERED=1
      - ALLOWED_ORIGIN=${ALLOWED_ORIGIN:-*}
    restart: unless-stopped
